
language: node_js

node_js:  
  - "12"

services:
  - postgresql

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_balloon_tests_tests;

before_script:
  - psql -c 'create database my_balloon_tests_tests;' -U postgres
  - psql -U postgres -d my_balloon_tests_tests -a -f the-balloon.sql
